In [2]:
import numpy as np

# Створення різних типів масивів

In [3]:
arr_arange = np.arange(1,11)
arr_rand_int = np.random.randint(10, size = (4,4))
arr_rand_decimal = np.random.rand(4,4,2)
arr_zero = np.zeros((4,4))
arr_ones = np.ones((4,4))

In [4]:
print("Вектор за допомогою функціі arange:")
print(arr_arange)
print("Двомвимірний масив за допомогою функціі random.randint, що генерує цілі числа:")
print(arr_rand_int)
print("Трьохвимірний масив за допомогою функціі random.rand, що генерує десяткові числа:")
print(arr_rand_decimal)
print("Двомвимірний масив за допомогою функціі zeros, що генерує масив з нульовими елементами:")
print(arr_zero)
print("Двомвимірний масив за допомогою функцій ones, що генерує масив, який складається тільки з одиниць:")
print(arr_ones)

Вектор за допомогою функціі arange:
[ 1  2  3  4  5  6  7  8  9 10]
Двомвимірний масив за допомогою функціі random.randint, що генерує цілі числа:
[[4 9 7 2]
 [4 3 9 3]
 [2 0 6 6]
 [1 6 0 0]]
Трьохвимірний масив за допомогою функціі random.rand, що генерує десяткові числа:
[[[0.71094969 0.99523667]
  [0.02859071 0.85403974]
  [0.31044984 0.21843413]
  [0.73058981 0.61965306]]

 [[0.42607411 0.79929107]
  [0.17189483 0.92953698]
  [0.32210079 0.49328288]
  [0.62117218 0.40825532]]

 [[0.05735405 0.99397833]
  [0.90389241 0.03742141]
  [0.7412766  0.8166447 ]
  [0.54777745 0.80149123]]

 [[0.24270526 0.82676551]
  [0.58097517 0.4239511 ]
  [0.22206869 0.83837986]
  [0.47096564 0.53377324]]]
Двомвимірний масив за допомогою функціі zeros, що генерує масив з нульовими елементами:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Двомвимірний масив за допомогою функцій ones, що генерує масив, який складається тільки з одиниць:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1

# Зберігання у файл та читання з файлу     

In [5]:
arr = np.save('saving.npy',arr_arange)
output = np.load('saving.npy')
print("Зчитаний вектор з файлу:", output)

Зчитаний вектор з файлу: [ 1  2  3  4  5  6  7  8  9 10]


# Різні операції з матрицями

In [6]:
arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [9, 10]])
print("Перша матриця:", arr1)
print("Друга матриця:", arr2)
print ("Сума двох матриць:")
print (np.add(arr1,arr2))
print ("Різниця двох матриць: ")
print (np.subtract(arr1,arr2))
print ("Частка двох матриць: ")
print (np.divide(arr1,arr2))
print ("Множення матриць поелементно: ")
print (np.multiply(arr1,arr2))
print ("Добуток матриць: ")
print (np.dot(arr1,arr2))
print ("Добуток матриці на скаляр: ")
print (3*arr1)
print ("Квадратний корінь з  першої матриці:")
print (np.sqrt(arr1))
print ("Сума елементів другої матриці: ")
print (np.sum(arr2))
print ("Сума елементів по стовбцям першої матриці: ")
print (np.sum(arr1,axis=0))
print ("Сума елементів по рядкам другої матриці: ")
print (np.sum(arr2,axis=1))
print ("Транспонування першої матриці: ")
print (np.transpose(arr1))

Перша матриця: [[1 2]
 [4 5]]
Друга матриця: [[ 7  8]
 [ 9 10]]
Сума двох матриць:
[[ 8 10]
 [13 15]]
Різниця двох матриць: 
[[-6 -6]
 [-5 -5]]
Частка двох матриць: 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
Множення матриць поелементно: 
[[ 7 16]
 [36 50]]
Добуток матриць: 
[[25 28]
 [73 82]]
Добуток матриці на скаляр: 
[[ 3  6]
 [12 15]]
Квадратний корінь з  першої матриці:
[[1.         1.41421356]
 [2.         2.23606798]]
Сума елементів другої матриці: 
34
Сума елементів по стовбцям першої матриці: 
[5 7]
Сума елементів по рядкам другої матриці: 
[15 19]
Транспонування першої матриці: 
[[1 4]
 [2 5]]


# Видалення даних у numpy

In [10]:
vector = np.arange(1,11)
print("Початковий вектор:")
print(vector)
vector_new = np.delete(vector,[1,3,5])
print("Вектор після видалення елементів:")
print(vector_new)

Початковий вектор:
[ 1  2  3  4  5  6  7  8  9 10]
Вектор після видалення елементів:
[ 1  3  5  7  8  9 10]
