In [24]:
import tensorflow as tf
import numpy as np

# Створення скаляру

In [5]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

# Створення масиву

In [9]:
vector = tf.constant([1,2,3,4,5])
vector

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 5]])>

# Використання функції ndim

In [10]:
print("Розмірність масиву:", vector.ndim)

Розмірність масиву: 2


# Створення матриці

In [21]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5],
                    [2, 5,16]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 30,  5],
       [ 3,  4,  5],
       [ 2,  5, 16]])>

# Використання функції reshape

In [22]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5]])
matrix = tf.reshape(matrix, shape=(3, 2))
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 30],
       [ 5,  3],
       [ 4,  5]])>

# Конвертування тензору у numpy масив

In [25]:
vector = tf.constant([1,2,3,4,5])
np.array(vector), type(np.array(vector))

(array([1, 2, 3, 4, 5]), numpy.ndarray)

# One-hot encoding у tensorflow

In [28]:
vector = tf.constant([1,2,3,4,5])
tf.one_hot(vector, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Операції між матрицями

### 1) Множення:

In [13]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5],
                    [2, 5,16]])
matrix2 = tf.constant([[1, 20, 15],
                    [8, 4,7],
                    [3, 8, 4]])
result = tf.matmul(matrix, matrix2)
result

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[275, 560, 530],
       [ 50, 116,  93],
       [ 90, 188, 129]])>

### 2) Множення матриці на скаляр:

In [14]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5],
                    [2, 5,16]])
scalar = tf.constant(3)
result = matrix*scalar
result

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[60, 90, 15],
       [ 9, 12, 15],
       [ 6, 15, 48]])>

### 3) Cума матриць

In [15]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5],
                    [2, 5,16]])
matrix2 = tf.constant([[1, 20, 15],
                    [8, 4,7],
                    [3, 8, 4]])
result = tf.add(matrix, matrix2)
result

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 50, 20],
       [11,  8, 12],
       [ 5, 13, 20]])>

### 4) Різниця матриць

In [16]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5],
                    [2, 5,16]])
matrix2 = tf.constant([[1, 20, 15],
                    [8, 4,7],
                    [3, 8, 4]])
result = tf.subtract(matrix, matrix2)
result

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 19,  10, -10],
       [ -5,   0,  -2],
       [ -1,  -3,  12]])>

### 5) Ділення матриць

In [17]:
matrix= tf.constant([[20, 30, 5],
                    [3, 4,5],
                    [2, 5,16]])
matrix2 = tf.constant([[1, 20, 15],
                    [8, 4,7],
                    [3, 8, 4]])
result = tf.divide(matrix, matrix2)
result

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[20.        ,  1.5       ,  0.33333333],
       [ 0.375     ,  1.        ,  0.71428571],
       [ 0.66666667,  0.625     ,  4.        ]])>